# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a096f9221871ddfeeecbfbae8b34f1211e8010e416e4b4065770db91c4bc4a33a677e9c37284245b01bcf31cac19c90a2638ca9bb4e637c67c3694aae0fd4bb4

test:
  secret_key_base: fd55290b52ee8f6afae5d27ee5049a39c1e64768e077648e590b854f86ff2a6883ae7d48b8294f5a732cb8f3b3e0422c44d675859f275dc0faa2a0c30d82bad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
